import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { CardMedia } from '@mui/material'
import Divider from '@mui/material/Divider'
import FloatingButton from '../components/FloatingButton'
import Card from '../components/WineCard'
import React from 'react'
import CartButton from '../components/CartButton'
import TemporaryDrawer from '../components/Drawer'
import { WinesData } from '../services/sheet'

const api = [
  {
    nombre: 'Vino 1',
    precio: '$5',
    imagen:
      'https://www.deliargentina.com/image/cache/catalog/product/vino/vino-catena-malbec-argentina/vino-catena-malbec-argentina-600x600.png',
    categoria: 'Vino',
    bodega: 'Bodega 1',
  },
  {
    nombre: 'Vino 2',
    precio: '$6',
    imagen:
      'https://www.deliargentina.com/image/cache/catalog/product/vino/vino-catena-malbec-argentina/vino-catena-malbec-argentina-600x600.png',
    categoria: 'Vino',
    bodega: 'Bodega 2',
  },
  {
    nombre: 'Vino 3',
    precio: '$5.40',
    imagen:
      'https://www.deliargentina.com/image/cache/catalog/product/vino/vino-catena-malbec-argentina/vino-catena-malbec-argentina-600x600.png',
    categoria: 'Vino',
    bodega: 'Bodega 3',
  },
  {
    nombre: 'Vino 4',
    precio: '$12',
    imagen:
      'https://www.deliargentina.com/image/cache/catalog/product/vino/vino-catena-malbec-argentina/vino-catena-malbec-argentina-600x600.png',
    categoria: 'Vino',
    bodega: 'Bodega 4',
  },
]

type Anchor = 'top' | 'left' | 'bottom' | 'right'

export default function Home() {
  const [state, setState] = React.useState({ left: false })
  const [input, setInput] = React.useState([])
  const [api, setApi] = React.useState([])

  React.useEffect(() => {
    const data = WinesData().then(result => {
      setApi(result)
    })
  }, [])

  const toggleDrawer = (anchor: Anchor, open: boolean) => (event: React.KeyboardEvent | React.MouseEvent) => {
    if (
      event.type === 'keydown' &&
      ((event as React.KeyboardEvent).key === 'Tab' || (event as React.KeyboardEvent).key === 'Shift')
    ) {
      return
    }

    setState({ ...state, [anchor]: open })
  }
  return (
    <>
      <Head>
        <title>Tinta Roja</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', flexDirection: 'column' }}>
        <div
          style={{
            width: '100%',
            height: '30vh',
            margin: 'none',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundImage: 'url(background.svg)',
          }}
        >
          <label
            style={{
              fontFamily: 'Montserrat',
              fontWeight: 700,
              fontSize: '64px',
              textTransform: 'uppercase',
            }}
          >
            Tinta <label style={{ color: '#572364' }}>roja</label>
          </label>
        </div>
      </main>
      <Divider />
      <div style={{ textAlign: 'center', marginTop: '12px' }}>
        <label
          style={{
            fontFamily: 'Raleway',
            fontWeight: 700,
            fontSize: '28px',
            textTransform: 'uppercase',
          }}
        >
          Especialmente elegidos por y para <label style={{ color: '#572364' }}>ustedes</label>:
        </label>
      </div>
      <div
        style={{
          display: 'flex',
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
          flexWrap: 'wrap',
          marginTop: '60px',
        }}
      >
        {Array.isArray(api) &&
          api.map((product: any) => (
            <Card
              key={product['nombre']}
              name={product['nombre']}
              price={product['precio']}
              image={product['imagen']}
              bodega={product['bodega']}
              input={input}
              setInput={setInput}
            />
          ))}
      </div>
      <label onClick={() => setState({ left: true })}>
        <CartButton />
      </label>
      <FloatingButton />
      <TemporaryDrawer
        state={state}
        setState={setState}
        toggleDrawer={toggleDrawer}
        input={input}
        setInput={setInput}
      />
    </>
  )
}
